import type { AppState } from './types'

const weekdays = [true, true, true, true, true, false, false]

function extraIep(ilce: string) {
  return {
    uygulamaIlce: ilce,
    ogrenimAlt: 'İlköğretim',
    ogrenimUst: 'Lisans',
    yasMin: 18,
    yasMax: 50,
    kursDurum: '',
    basvuruTarih: '2026-09-14',
    tatilGunleri: [] as string[],
    fiiliDortteBirlikTarih: '2026-10-08',
    iepKesSayisi: 92,
    kontenjanSayisi: 28,
    kontenjanKullanilan: 8,
  }
}

export const seedState: AppState = {
  employer: {
    unvan: 'Örnek Üretim A.Ş.',
    vergiNo: '1234567890',
    sgkSicilNo: '1234501012345678901234',
    il: 'İstanbul',
    ilce: 'Pendik',
    adres: 'Sanayi Mah. Örnek Cad. No:12',
    yetkili: 'Mehmet Yılmaz',
    telefon: '0216 000 00 00',
    eposta: 'ik@ornekuretim.example',
  },
  workplaces: [
    {
      id: 'firma-pendik',
      unvan: 'Örnek Üretim A.Ş. — Pendik Atölye',
      sgkSicilNo: '1234501012345678901234',
      il: 'İstanbul',
      ilce: 'Pendik',
      adres: 'Sanayi Mah. Örnek Cad. No:12',
    },
    {
      id: 'firma-tuzla',
      unvan: 'Örnek Üretim A.Ş. — Tuzla Depo',
      sgkSicilNo: '1234501012345678909999',
      il: 'İstanbul',
      ilce: 'Tuzla',
      adres: 'Organize Sanayi 2. Cad. No:8',
    },
  ],
  programs: [
    {
      id: 'prg-iep-01',
      firmaId: 'firma-pendik',
      ad: 'CNC Operatörü İşbaşı Eğitim Programı',
      iskurDosyaNo: 'IEP-2026-03412',
      kursNo: 'K-2026-881',
      meslek: 'CNC Tezgah Operatörü',
      meslekKodu: '7223.05',
      kontenjan: 8,
      baslangic: '2026-09-01',
      bitis: '2026-12-01',
      gunlukSaat: 8,
      toplamGun: 90,
      status: 'devam',
      aciklama: 'İŞKUR İEP kapsamında atölye içi uygulamalı eğitim.',
      kontenjanIl: 'İstanbul',
      kontenjanIlce: 'Pendik',
      uygulamaIl: 'İstanbul',
      ...extraIep('Pendik'),
      uygulamaAdres: 'Sanayi Mah. Örnek Cad. No:12 Atölye-1',
      ayniMeslekteSigortali: 'evet',
      imalatBilisim: 'evet',
      tehlikeliMeslek: 'hayir',
      programIlani: 'hayir',
      erkekKursiyer: 5,
      kadinKursiyer: 3,
      calisanSayisi: 42,
      kalanKontenjan: 8,
      ilkHafta: weekdays,
      devamHafta: weekdays,
      sonHafta: weekdays,
      belgeler: [],
    },
    {
      id: 'prg-iep-02',
      firmaId: 'firma-pendik',
      ad: 'Kaynakçı İşbaşı Eğitim Programı',
      iskurDosyaNo: 'IEP-2026-04188',
      kursNo: '',
      meslek: 'Gazaltı Kaynakçısı',
      meslekKodu: '7212.10',
      kontenjan: 6,
      baslangic: '2026-10-01',
      bitis: '2026-12-31',
      gunlukSaat: 8,
      toplamGun: 75,
      status: 'onaylandi',
      aciklama: 'Onaylandı; işbaşı bildirimleri bekleniyor.',
      kontenjanIl: 'İstanbul',
      kontenjanIlce: 'Pendik',
      uygulamaIl: 'İstanbul',
      ...extraIep('Pendik'),
      uygulamaAdres: 'Kaynak atölyesi',
      ayniMeslekteSigortali: 'evet',
      imalatBilisim: 'evet',
      tehlikeliMeslek: 'evet',
      programIlani: 'evet',
      erkekKursiyer: 4,
      kadinKursiyer: 2,
      calisanSayisi: 42,
      kalanKontenjan: 6,
      ilkHafta: weekdays,
      devamHafta: weekdays,
      sonHafta: weekdays,
      belgeler: [],
    },
    {
      id: 'prg-iep-03',
      firmaId: 'firma-tuzla',
      ad: 'Depo Sorumlusu İşbaşı Eğitim Programı',
      iskurDosyaNo: 'IEP-2026-02801',
      kursNo: 'K-2026-440',
      meslek: 'Depo Sorumlusu',
      meslekKodu: '4321.02',
      kontenjan: 4,
      baslangic: '2026-06-02',
      bitis: '2026-08-31',
      gunlukSaat: 8,
      toplamGun: 60,
      status: 'tamamlandi',
      aciklama: 'Program süresi doldu.',
      kontenjanIl: 'İstanbul',
      kontenjanIlce: 'Tuzla',
      uygulamaIl: 'İstanbul',
      ...extraIep('Tuzla'),
      uygulamaAdres: 'Merkez Depo',
      ayniMeslekteSigortali: 'hayir',
      imalatBilisim: 'hayir',
      tehlikeliMeslek: 'hayir',
      programIlani: 'hayir',
      erkekKursiyer: 3,
      kadinKursiyer: 1,
      calisanSayisi: 18,
      kalanKontenjan: 0,
      ilkHafta: weekdays,
      devamHafta: weekdays,
      sonHafta: weekdays,
      belgeler: [],
    },
  ],
  trainees: [
    {
      id: 'trn-01',
      programId: 'prg-iep-01',
      tcKimlikNo: '10000000146',
      ad: 'Ayşe',
      soyad: 'Demir',
      dogumTarihi: '1998-04-12',
      telefon: '0532 000 00 01',
      eposta: 'ayse.demir@example.com',
      meslek: 'CNC Tezgah Operatörü',
      status: 'devam',
    },
    {
      id: 'trn-02',
      programId: 'prg-iep-01',
      tcKimlikNo: '10000000154',
      ad: 'Can',
      soyad: 'Kaya',
      dogumTarihi: '2001-11-03',
      telefon: '0532 000 00 02',
      eposta: 'can.kaya@example.com',
      meslek: 'CNC Tezgah Operatörü',
      status: 'isbasi',
    },
    {
      id: 'trn-03',
      programId: 'prg-iep-01',
      tcKimlikNo: '10000000162',
      ad: 'Elif',
      soyad: 'Çelik',
      dogumTarihi: '1996-07-21',
      telefon: '0532 000 00 03',
      eposta: 'elif.celik@example.com',
      meslek: 'CNC Tezgah Operatörü',
      status: 'onaylandi',
    },
    {
      id: 'trn-04',
      programId: 'prg-iep-02',
      tcKimlikNo: '10000000170',
      ad: 'Burak',
      soyad: 'Şahin',
      dogumTarihi: '1994-01-30',
      telefon: '0532 000 00 04',
      eposta: 'burak.sahin@example.com',
      meslek: 'Gazaltı Kaynakçısı',
      status: 'onaylandi',
    },
    {
      id: 'trn-05',
      programId: 'prg-iep-02',
      tcKimlikNo: '10000000188',
      ad: 'Zeynep',
      soyad: 'Arslan',
      dogumTarihi: '1999-09-08',
      telefon: '0532 000 00 05',
      eposta: 'zeynep.arslan@example.com',
      meslek: 'Gazaltı Kaynakçısı',
      status: 'aday',
    },
    {
      id: 'trn-06',
      programId: 'prg-iep-03',
      tcKimlikNo: '10000000196',
      ad: 'Mert',
      soyad: 'Aydın',
      dogumTarihi: '1992-02-14',
      telefon: '0532 000 00 06',
      eposta: 'mert.aydin@example.com',
      meslek: 'Depo Sorumlusu',
      status: 'tamamlandi',
    },
  ],
  jobStarts: [
    {
      id: 'js-01',
      traineeId: 'trn-01',
      programId: 'prg-iep-01',
      isbasiTarihi: '2026-09-01',
      unvanGorev: 'CNC Operatör Adayı',
      calismaYeri: 'Pendik Atölye-1',
      vardiya: '08:00 – 17:00',
      sgkBildirimi: true,
      iskurBildirimDurumu: 'onaylandi',
      sozlesme: true,
      kimlikFotokopi: true,
      sgkIseGiris: true,
      notlar: 'İlk hafta oryantasyon tamamlandı.',
      createdAt: '2026-08-28T09:00:00.000Z',
    },
    {
      id: 'js-02',
      traineeId: 'trn-02',
      programId: 'prg-iep-01',
      isbasiTarihi: '2026-09-08',
      unvanGorev: 'CNC Operatör Adayı',
      calismaYeri: 'Pendik Atölye-1',
      vardiya: '08:00 – 17:00',
      sgkBildirimi: true,
      iskurBildirimDurumu: 'e_sube_isaretlendi',
      sozlesme: true,
      kimlikFotokopi: true,
      sgkIseGiris: true,
      notlar: 'e-Şube bildirimi işaretlendi, İŞKUR onayı bekleniyor.',
      createdAt: '2026-09-05T11:20:00.000Z',
    },
    {
      id: 'js-03',
      traineeId: 'trn-06',
      programId: 'prg-iep-03',
      isbasiTarihi: '2026-06-02',
      unvanGorev: 'Depo Sorumlusu Adayı',
      calismaYeri: 'Merkez Depo',
      vardiya: '08:00 – 17:00',
      sgkBildirimi: true,
      iskurBildirimDurumu: 'onaylandi',
      sozlesme: true,
      kimlikFotokopi: true,
      sgkIseGiris: true,
      notlar: 'Program tamamlandı.',
      createdAt: '2026-05-28T08:00:00.000Z',
    },
  ],
  attendance: [
    {
      id: 'att-01',
      traineeId: 'trn-01',
      tarih: '2026-09-14',
      durum: 'geldi',
      girisSaati: '07:58',
      cikisSaati: '17:02',
      aciklama: '',
    },
    {
      id: 'att-02',
      traineeId: 'trn-01',
      tarih: '2026-09-15',
      durum: 'geldi',
      girisSaati: '08:01',
      cikisSaati: '',
      aciklama: '',
    },
    {
      id: 'att-03',
      traineeId: 'trn-02',
      tarih: '2026-09-14',
      durum: 'izinli',
      girisSaati: '',
      cikisSaati: '',
      aciklama: 'Ücretsiz izin',
    },
    {
      id: 'att-04',
      traineeId: 'trn-02',
      tarih: '2026-09-15',
      durum: 'geldi',
      girisSaati: '08:05',
      cikisSaati: '',
      aciklama: '',
    },
  ],
}
